---
version: '3.3'
services:
  database:
    container_name: webapp_database
    image: 'mysql/mysql-server:8.0.23-1.1.19'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myschoolprojectpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: webapp_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "0.0.0.0:3306:3306"


# START OF EXAMPLE:
#  cache:
#    container_name: webapp_redis
#    image: redis:6.2-rc3-buster
#    ports:
#      - "0.0.0.0:6379:6379"
#    restart: always

#  webapp:
#    depends_on:
#       - database
#       - cache
#    container: thisismywebapp
#    image: myimage:latest
#    ports:
#      - "0.0.0.0:80:80"
#    restart: always
# END OF EXAMPLE

volumes:
    db_data: {}
